### ISSUE TITLE
Consulta import de peli.py en consultas.py

### ISSUE THREAD

**Issue by SSParzival** [IIC2233/Syllabus-2023-2#430]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/396)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/395)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tenía la curiosidad y traté de crear una función en peli.py que usara un elemento prohibido abiertamente, como for. Luego, en consultas.py importé dicha función, y fue utilizada. Pensé que el test de elementos prohibidos avisaría del error, pero no. Pregunto más que nada si habrá una forma de mejorar los tests para que ese caso quede detectado.

**Comment by victoriaatria** [comment]
Hola @SSParzival ! Como fue mencionado en las issues #405 y #419 , el script entregado es una versión preliminar de elementos prohibidos que son fácilmente detectables, pero no detecta todos los elementos prohibidos, por lo que se recomienda siempre revisar las issues y preguntar si algo no queda claro. Éxito en la tarea, quedo atenta si tienes más dudas :)

**Comment by SSParzival** [comment]
Hmmmm, estoy consciente de ello, mas, ¿no sería ventajoso modificar dicho script de la tarea para que sea más pertinente a la realidad? Considero que la existencia de demasiados casos bordes arruina enormemente la funcionalidad efectiva del test.

**Comment by victoriaatria** [comment]
Lo que pasa es que ese script es una guía inicial para los alumnos sobre los elementos prohibidos, y no tiene como objetivo verificar todos estos elementos. El script es un apoyo para ustedes, pero de todas maneras deberían primero guiarse por lo que dice el enunciado y por las dudas respondidas a través de las issues. Espero haya quedado más claro, quedo atenta por si quedan más dudas al respecto :)
