### ISSUE TITLE
problema con "elementos_prohibidos"

### ISSUE THREAD

**Issue by Utmite** [IIC2233/Syllabus-2023-2#431]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/396)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/395)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola para hacer la tarea 3 como se puede usar itertools use  itertools.tee en la siguiente linea: (los numeros es la linea)
```python
# Código modificado
x1, x2 = itertools.tee(coso)
```
El test de cosas prohibida me dice ""ComandoProhibidoError: Se ha hecho uso de "tuple", en: "./consultas.py", line 33. Como se indica en el enunciado, el uso de este comando implica nota mínima en la tarea."" y no se donde esta la tupla, o si es que itertools.tee esta prohibido
gracias por su timepo

Edit por ayudante: Modificación de código para no incumplir las reglas del foro.

**Comment by Utmite** [comment]
Al realizar pruebas, noté que desempaquetar utilizando la expresión `x, y = itertools.tee(coso)` está prohibido y genera problemas. Sin embargo, al emplear la expresión x` = itertools.tee(coso)`, no se presentan inconvenientes.

Esto es intencional o es un error de su test?

**Comment by jtlledo** [comment]
Hola @Utmite! Efectivamente, no está permitido desempaquetar utilizando la expresión que mencionas. Te recomiendo que guardes todo dentro de una variable para después separar a mano las variables que necesites con indexación. Un ejemplo de esto sería lo siguiente:
```
x = itertools.tee(algo)
x1 = x[0]
x2 = x[1]
```
Por último, recuerda que está estrictamente prohibido subir código de una evaluación al foro durante el desarrollo de esta, debido a que atenta directamente contra la integridad académica.

**Comment by csilval** [comment]
Hola!

Dado que el código de la pregunta original no está, me costó entender la issue.
Se pueden desempaquetar listas, tuples, etc (creadas legalmente) en varias variables?

Por ejemplo:
var_1, var_2 = lista

donde lista es una lista de dos elementos creada por comprension.

**Comment by jtlledo** [comment]
Hola @csilval! Acabo de modificar el código de la pregunta original para que se entienda mejor, pero justamente lo que mencionas __no está permitido__, dado que levanta error en los tests. Quedamos atentos ante cualquier duda!

**Comment by jtlledo** [comment]
Hola @csilval! Acabo de modificar el código de la pregunta original para que se entienda mejor, pero justamente lo que mencionas __no está permitido__ en el caso de tuplas, dado que levanta error en los tests. En otros casos, por ejemplo en listas, se permite slicing, por lo que es recomendable usarlo. Quedamos atentos ante cualquier duda!
